"""Safety layer: hard caps, working hours and the gate every action passes.

`limits` does the arithmetic and `gate` makes the decision. CORE-05 adds a
`detect` module for challenge and interstitial detection alongside them, so
imports here stay one flat list per module rather than a hierarchy that would
need rearranging to fit it in.
"""

from linkedin_mcp.core.config import (
    APPROVAL_REQUIRED_ACTIONS,
    DEDUPE_WINDOW_DAYS,
    GLOBAL_DAILY_CEILING,
    GLOBAL_HOURLY_CEILING,
    HARD_CEILINGS,
    METERED_ACTIONS,
    PENDING_INVITE_CEILING,
    UNMETERED_ACTIONS,
    ActionCeiling,
    ceiling_for,
    profile_view_action,
)
from linkedin_mcp.safety.gate import (
    AccountChallenged,
    AccountCooldown,
    AccountLoggedOut,
    AccountPaused,
    ActionDisabled,
    ApprovalRequired,
    Blacklisted,
    DailyCapReached,
    DuplicateAction,
    HourlyCapReached,
    Lease,
    PendingInviteCeilingReached,
    SafetyError,
    SafetyGate,
    SafetyRefusal,
    UnknownAccountError,
    WarmupLimit,
    WeeklyCapReached,
    WorkingHoursClosed,
    acquire,
    get_gate,
    guard_action,
    reset_gate,
    set_gate,
)
from linkedin_mcp.safety.limits import (
    AccountLimit,
    Budget,
    WorkingWindow,
    account_limit,
    actions_in_window,
    daily_budget,
    daily_jitter_fraction,
    global_actions_in_window,
    global_daily_budget,
    hourly_budget,
    is_within_working_hours,
    metered_universe,
    pending_invites,
    ramp_up_cap,
    ramp_up_fraction,
    shrink_for_jitter,
    weekly_budget,
    working_windows,
)

__all__ = [
    "APPROVAL_REQUIRED_ACTIONS",
    "AccountChallenged",
    "AccountCooldown",
    "AccountLimit",
    "AccountLoggedOut",
    "AccountPaused",
    "ActionCeiling",
    "ActionDisabled",
    "ApprovalRequired",
    "Blacklisted",
    "Budget",
    "DEDUPE_WINDOW_DAYS",
    "DailyCapReached",
    "DuplicateAction",
    "GLOBAL_DAILY_CEILING",
    "GLOBAL_HOURLY_CEILING",
    "HARD_CEILINGS",
    "HourlyCapReached",
    "Lease",
    "METERED_ACTIONS",
    "PENDING_INVITE_CEILING",
    "PendingInviteCeilingReached",
    "SafetyError",
    "SafetyGate",
    "SafetyRefusal",
    "UNMETERED_ACTIONS",
    "UnknownAccountError",
    "WarmupLimit",
    "WeeklyCapReached",
    "WorkingHoursClosed",
    "WorkingWindow",
    "account_limit",
    "acquire",
    "actions_in_window",
    "ceiling_for",
    "daily_budget",
    "daily_jitter_fraction",
    "get_gate",
    "global_actions_in_window",
    "global_daily_budget",
    "guard_action",
    "hourly_budget",
    "is_within_working_hours",
    "metered_universe",
    "pending_invites",
    "profile_view_action",
    "ramp_up_cap",
    "ramp_up_fraction",
    "reset_gate",
    "set_gate",
    "shrink_for_jitter",
    "weekly_budget",
    "working_windows",
]
